### ISSUE TITLE
Button Ativo

### ISSUE THREAD

**Issue by Wander27Souza** [willian-nascimento/AppFormulario#8]
Ajustar seleção, aonde o usuário deve selecionar as opções e mudarem conforme a cor principal em educação.
@ElbertRibeiro 
![image](https://user-images.githubusercontent.com/48796830/159128521-0946120a-1a23-42be-b1cb-cd0c684458c9.png)

**Comment by ElbertRibeiro** [comment]
@Wander27Rodrigues  essa estrutura ja está criada?

se sim, informar o arquivo e linha
