### ISSUE TITLE
Espaço 

### ISSUE THREAD

**Issue by Wander27Souza** [willian-nascimento/AppFormulario#9]
Erro no espaçamento @ElbertRibeiro 

![image](https://user-images.githubusercontent.com/48796830/159128626-bacc9f34-8dc6-47cd-ab8b-09223ab40aef.png)

![image](https://user-images.githubusercontent.com/48796830/159128648-aa847a65-fefe-40e5-8493-057166eddeac.png)

**Comment by ElbertRibeiro** [comment]
#13
